In [1]:
""" Section A """
#list

list1 = [22,44,33,11,77]
list1

[22, 44, 33, 11, 77]

In [2]:
list1.append(81)
list1

[22, 44, 33, 11, 77, 81]

In [7]:
list2 = ['Akanksha','Tom']

In [8]:
list1.extend(list2)
list1

[22, 44, 33, 11, 77, 81, 'Akanksha', 'Tom']

In [15]:
list1.insert(2,12)
list1

[22, 44, 12, 12, 12, 11, 77, 81, 'Akanksha', 'Tom']

In [14]:
list1.remove(33)
list1

[22, 44, 12, 12, 11, 77, 81, 'Akanksha', 'Tom']

In [16]:
list1.pop()
list1

[22, 44, 12, 12, 12, 11, 77, 81, 'Akanksha']

In [22]:
list1.index(22)


0

In [21]:
list1.count(12)

3

In [24]:
list1.clear()
list1

[]

In [26]:
list3 = ['Gaurang','Akanksha',"pratiksha",'Ganesh']
list3.sort()
list3

['Akanksha', 'Ganesh', 'Gaurang', 'pratiksha']

In [27]:
list3.reverse()
list3

['pratiksha', 'Gaurang', 'Ganesh', 'Akanksha']

In [28]:
# Tuple
tuple1 = ("tom","som","piyush")
tuple1

('tom', 'som', 'piyush')

In [30]:
tuple1[1] = "Akanksha"
tuple1

TypeError: 'tuple' object does not support item assignment

In [ ]:
""" in tuple we cannot changed or any implement because tuple is immutable that the reason"""

In [32]:
#sets
fruits = {
    'Apple':1 , 'Banana':2 ,
    "Mango":3, 'Peru':1
    }
fruits

{'Apple': 1, 'Banana': 2, 'Mango': 3, 'Peru': 1}

In [ ]:
"""In Sets includes key:values in that we cannot give the duplicate key but we can create the duplicate values."""

In [34]:
# Dictonary

Data = {
    "name":"Akanksha",
    "age":21,
    "city":"Pune"
}
Data


{'name': 'Akanksha', 'age': 21, 'city': 'Pune'}

In [36]:
Data.update({'age':34})
Data

{'name': 'Akanksha', 'age': 34, 'city': 'Pune'}

In [41]:
Data['Email'] = 'akankshaamale@gmail.com'
Data

{'name': 'Akanksha',
 'age': 34,
 'city': 'Pune',
 'Email': 'akankshaamale@gmail.com'}

In [45]:
# Conditionl statement

marks = int(input("Enter the Marks"))
if marks >= 90:
    print("Grade : A")
elif marks >= 75:
    print("Grade : B")
elif marks >= 50:
    print("Grade : C")
else:
    print("Fail")

Enter the Marks 55


Grade : C


In [48]:
Number = int(input("Enter the number"))

if Number > 0 or Number % 2 == 0:
    print("Number is positive")
elif Number == 0:
    print("zero")
else:
    print("Number is negative")

Enter the number 3


Number is positive


In [49]:
""" Section B """

import numpy as np

In [66]:
# A scalar : 0D array
scalar = np.array(5)
print("scalar :", scalar)
print("scalar shape :", scalar.shape,"\n")

# 1D array
array1 = np.array([1,2,3,4,5])
print("1D Array : ", array1)
print("1D Array shape : ", array1.shape, "\n")

#2D array
array2 = np.array([[10,30,55],[22,15,3]])
print("2D Array : ", "\n",array2)
print("2D Array shape : ", array2.shape)

scalar : 5
scalar shape : () 

1D Array :  [1 2 3 4 5]
1D Array shape :  (5,) 

2D Array :  
 [[10 30 55]
 [22 15  3]]
2D Array shape :  (2, 3)


In [71]:
array = np.random.randint(0,100,size=(4,4))
array

array([[54, 59, 30, 72],
       [29,  1, 19, 94],
       [13,  5, 89,  3],
       [ 0,  6, 51, 47]], dtype=int32)

In [76]:
import pandas as pd

In [81]:
data = np.array([[2,5,7],[9,55,3],[89,33,11]])
data

array([[ 2,  5,  7],
       [ 9, 55,  3],
       [89, 33, 11]])

In [82]:
df = pd.DataFrame(data)
df

0   1   2
0   2   5   7
1   9  55   3
2  89  33  11

In [84]:
df= pd.DataFrame(data,columns=['A','B','C'])
df

A   B   C
0   2   5   7
1   9  55   3
2  89  33  11

In [1]:
# section C


import pandas as pd
import numpy as np

In [3]:
data = {
    'Name' : ['Akanksha','Rutuja','Ashwini','Aditi','Ishwari','Yasha','Arpit','Avanti','Akanksha','Shravni'],
    'Age' : [21,33,np.nan, 33,50,44,22,np.nan,21,55],
    'City' : ['Amt','murtijapur','ch.bz','pune','Nagpur','pusad','Mumbai','Adgaon','Amt','darypur'],
    'Salary' : [1000000,40000,20000,44000,np.nan,50000,np.nan,440300,1000000,np.nan]
}

In [4]:
df = pd.DataFrame(data)
df

Name   Age        City     Salary
0  Akanksha  21.0         Amt  1000000.0
1    Rutuja  33.0  murtijapur    40000.0
2   Ashwini   NaN       ch.bz    20000.0
3     Aditi  33.0        pune    44000.0
4   Ishwari  50.0      Nagpur        NaN
5     Yasha  44.0       pusad    50000.0
6     Arpit  22.0      Mumbai        NaN
7    Avanti   NaN      Adgaon   440300.0
8  Akanksha  21.0         Amt  1000000.0
9   Shravni  55.0     darypur        NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     8 non-null      float64
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [6]:
df.describe()

Age          Salary
count   8.00000        7.000000
mean   34.87500   370614.285714
std    13.49537   454388.865872
min    21.00000    20000.000000
25%    21.75000    42000.000000
50%    33.00000    50000.000000
75%    45.50000   720150.000000
max    55.00000  1000000.000000

In [9]:
print(df[['Name','City']])

       Name        City
0  Akanksha         Amt
1    Rutuja  murtijapur
2   Ashwini       ch.bz
3     Aditi        pune
4   Ishwari      Nagpur
5     Yasha       pusad
6     Arpit      Mumbai
7    Avanti      Adgaon
8  Akanksha         Amt
9   Shravni     darypur


In [14]:
df.drop(columns=['City'], inplace = True)

In [15]:
df

Name   Age     Salary
0  Akanksha  21.0  1000000.0
1    Rutuja  33.0    40000.0
2   Ashwini   NaN    20000.0
3     Aditi  33.0    44000.0
4   Ishwari  50.0        NaN
5     Yasha  44.0    50000.0
6     Arpit  22.0        NaN
7    Avanti   NaN   440300.0
8  Akanksha  21.0  1000000.0
9   Shravni  55.0        NaN

In [24]:
salary_mean = df['Salary'].mean()

In [18]:
df['Salary'].value_counts()

Salary
1000000.0    2
40000.0      1
20000.0      1
44000.0      1
50000.0      1
440300.0     1
Name: count, dtype: int64

In [25]:
df['Salary'].fillna(salary_mean, inplace=True)

In [26]:
df

Name   Age          Salary
0  Akanksha  21.0  1000000.000000
1    Rutuja  33.0    40000.000000
2   Ashwini   NaN    20000.000000
3     Aditi  33.0    44000.000000
4   Ishwari  50.0   370614.285714
5     Yasha  44.0    50000.000000
6     Arpit  22.0   370614.285714
7    Avanti   NaN   440300.000000
8  Akanksha  21.0  1000000.000000
9   Shravni  55.0   370614.285714

In [28]:
df.isna().sum()

Name      0
Age       2
Salary    0
dtype: int64

In [31]:
df.shape

(10, 3)

In [32]:
df.drop_duplicates(inplace = True)

In [33]:
df

Name   Age          Salary
0  Akanksha  21.0  1000000.000000
1    Rutuja  33.0    40000.000000
2   Ashwini   NaN    20000.000000
3     Aditi  33.0    44000.000000
4   Ishwari  50.0   370614.285714
5     Yasha  44.0    50000.000000
6     Arpit  22.0   370614.285714
7    Avanti   NaN   440300.000000
9   Shravni  55.0   370614.285714

In [34]:
df.shape

(9, 3)